spring:
  datasource:
    url: jdbc:mysql://172.16.32.128:3306/general?serverTimezone=UTC&useUnicode=true&useSSL=false&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: a8eed
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    open-in-view: true
  thymeleaf:
    cache: false
    mode: HTML5
    encoding: UTF-8
